<?php
$this->headTitle('Manage Pages');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Admin'=>$this->url('home')
            ]);
?>

<h1>Manage Pages</h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('pages', ['action'=>'add']); ?>">
    New Page
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Page Title</th>
        <th>Date Created</th>
        <th>Status</th>        
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($pages as $page): ?>
    
    <tr>
        <td><?= $this->escapeHtml($page->getId()); ?></td>
        <td>
            <a href="<?= $this->url('pages', ['action'=>'view', 'id'=>$page->getId()]); ?>">
                <?= $this->escapeHtml($page->getTitle()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($page->getDateCreated()); ?></td>        
        <td><?= $this->escapeHtml($pageManager->getPageStatusAsString($page)); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('pages', 
                    ['action'=>'edit', 'id'=>$page->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-danger" href="<?= $this->url('pages',
                    ['action'=>'delete', 'id'=>$page->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Delete
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>