<?php
$this->headTitle('New Page');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Edit Page'=>$this->url('pages', ['action'=>'edit'])
            ]);

$form = $this->form;
$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Enter page title here'
    ]);
$form->get('content')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Type content here',
    'rows'=>6
    ]);
$form->get('tags')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'comma, separated, list, of, tags'
    ]);
$form->get('status')->setAttributes([
    'class'=>'form-control'   
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submit')->setValue('Save');
$form->prepare();

?>

<h1>Edit Page</h1>

<p>
    Please fill out the following form and click the <i>Save</i> button.
</p>

<div class="row">
    <div class="col-md-12">
        <?= $this->form()->openTag($form); ?>
            <div class="col-md-8">
                <div class="form-group">
                    <?= $this->formLabel($form->get('title')); ?>
                    <?= $this->formElement($form->get('title')); ?>
                    <?= $this->formElementErrors($form->get('title')); ?>                  
                </div>
                
                <div class="form-group">
                    <?= $this->formLabel($form->get('content')); ?>
                    <?= $this->formElement($form->get('content')); ?>
                    <?= $this->formElementErrors($form->get('content')); ?>                  
                </div>
            </div>
            
            <div class="col-md-3">
                <div class="form-group">
                    <?= $this->formLabel($form->get('tags')); ?>
                    <?= $this->formElement($form->get('tags')); ?>
                    <?= $this->formElementErrors($form->get('tags')); ?>                  
                    <p class="help-block">Separate tags with comma.</p>
                </div>
                
                <div class="form-group">
                    <?= $this->formLabel($form->get('status')); ?>
                    <?= $this->formElement($form->get('status')); ?>
                    <?= $this->formElementErrors($form->get('status')); ?>                  
                </div>
                <div class="form-group">
                    <?= $this->formElement($form->get('submit')); ?>
                    <?= $this->formElement($form->get('preview')); ?>
                </div>
            </div>
            
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>    