<?php
$this->headTitle('Pages');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Pages</h1>

<div class="row">
    
    <div class="col-md-8">

    <?php foreach($pages as $page): ?>

    <h3>
        <a href="<?= $this->url('pages', ['action'=>'view', 'id'=>$page->getId()]); ?>">
            <?= $this->escapeHtml($page->getTitle()); ?>
        </a>    
    </h3>
    
    <p>
        Published: <?= $this->escapeHtml(date('jS \of F Y', strtotime($page->getDateCreated()))); ?> 
        | Tags: <?= $this->escapeHtml($pageManager->convertTagsToString($page)); ?>   
    </p>    
        
    <p class="comments-header">
        <?= $this->escapeHtml($pageManager->getCommentCountStr($page)); ?> | 
        <a href="<?= $this->url('pages', ['action'=>'view', 'id'=>$page->getId()],
                ['fragment'=>'comment']); ?>">
            Add new comment
        </a>
    </p>

    <p>    
        <?= $this->escapeHtml($page->getContent()); ?>
    </p>

    <?php endforeach; ?>

    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Popular Tags</h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->tagCloud as $tagName=>$frequency): ?>
                
                <a href="<?= $this->url('application', ['action'=>'index'],
                    ['query'=>['tag'=>$tagName]]); ?>">                   
        
                    <span style="font-size:<?= $this->escapeHtml(0.9+$frequency*3) ?>em">
                        <?= $this->escapeHtml($tagName); ?>
                    </span>
                
                </a>    
                    
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>


